#
# This file is the default set of rules to compile a Pebble application.
#
# Feel free to customize this to your needs.
#
import os
import os.path

top = "."
out = "build"


def options(ctx):
    ctx.load("pebble_sdk")


def configure(ctx):
    """
    This method is used to configure your build. ctx.load(`pebble_sdk`) automatically configures
    a build for each valid platform in `targetPlatforms`. Platform-specific configuration: add your
    change after calling ctx.load('pebble_sdk') and make sure to set the correct environment first.
    Universal configuration: add your change prior to calling ctx.load('pebble_sdk').
    """
    ctx.load("pebble_sdk")


def _write_build_overrides():
    """Write build/build_overrides.auto.js from environment variables.

    Tests pass PEBBLE_TEST_OSM_BASE_URL and PEBBLE_TEST_ARRIVAL_THRESHOLD_M
    via env vars.  When set, those values end up in the generated module so
    that PKJS code can pick them up at runtime.  When unset the file still
    gets written (with null placeholders) so webpack can always resolve the
    require.
    """
    osm_url = os.environ.get("PEBBLE_TEST_OSM_BASE_URL")
    threshold = os.environ.get("PEBBLE_TEST_ARRIVAL_THRESHOLD_M")
    gps_max_age = os.environ.get("PEBBLE_TEST_GPS_MAX_AGE_MS")
    osm_auth_url = os.environ.get("PEBBLE_TEST_OSM_AUTH_BASE_URL")
    client_id = os.environ.get("PEBBLE_TEST_CLIENT_ID")
    osm_token = os.environ.get("PEBBLE_TEST_OSM_TOKEN")

    osm_val = "'{}'".format(osm_url) if osm_url else "null"
    thr_val = threshold if threshold else "null"
    gps_val = gps_max_age if gps_max_age else "null"
    auth_val = "'{}'".format(osm_auth_url) if osm_auth_url else "null"
    client_val = "'{}'".format(client_id) if client_id else "null"
    token_val = "'{}'".format(osm_token) if osm_token else "null"

    os.makedirs("build", exist_ok=True)
    with open(os.path.join("build", "build_overrides.auto.js"), "w") as f:
        f.write("/* Auto-generated by wscript. Do not edit manually. */\n")
        f.write("module.exports = {\n")
        f.write("  ARRIVAL_THRESHOLD_M: {},\n".format(thr_val))
        f.write("  OSM_BASE_URL: {},\n".format(osm_val))
        f.write("  GPS_MAX_AGE_MS: {},\n".format(gps_val))
        f.write("  OSM_AUTH_BASE_URL: {},\n".format(auth_val))
        f.write("  CLIENT_ID: {},\n".format(client_val))
        f.write("  OSM_TOKEN: {},\n".format(token_val))
        f.write("};\n")


def build(ctx):
    ctx.load("pebble_sdk")

    _write_build_overrides()

    build_worker = os.path.exists("worker_src")
    binaries = []

    cached_env = ctx.env
    for platform in ctx.env.TARGET_PLATFORMS:
        ctx.env = ctx.all_envs[platform]
        ctx.set_group(ctx.env.PLATFORM_NAME)
        app_elf = "{}/pebble-app.elf".format(ctx.env.BUILD_DIR)
        ctx.pbl_build(
            source=ctx.path.ant_glob("src/c/**/*.c"), target=app_elf, bin_type="app"
        )

        if build_worker:
            worker_elf = "{}/pebble-worker.elf".format(ctx.env.BUILD_DIR)
            binaries.append(
                {"platform": platform, "app_elf": app_elf, "worker_elf": worker_elf}
            )
            ctx.pbl_build(
                source=ctx.path.ant_glob("worker_src/c/**/*.c"),
                target=worker_elf,
                bin_type="worker",
            )
        else:
            binaries.append({"platform": platform, "app_elf": app_elf})
    ctx.env = cached_env

    ctx.set_group("bundle")
    ctx.pbl_bundle(
        binaries=binaries,
        js=ctx.path.ant_glob(
            [
                "src/pkjs/**/*.js",
                "src/pkjs/**/*.json",
                "src/common/**/*.js",
                "src/config/**/*.js",
            ]
        ),
        js_entry_file="src/pkjs/index.js",
    )
